# Generated by Django 4.2.30 on 2026-06-01 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0025_alter_community_default_lt_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(db_index=True, max_length=255, verbose_name='ページパス')),
                ('date', models.DateField(db_index=True, verbose_name='日付')),
                ('content_type', models.CharField(choices=[('community', '集会ページ'), ('event_detail', 'イベント詳細ページ')], max_length=20, verbose_name='コンテンツ種別')),
                ('object_id', models.PositiveIntegerField(verbose_name='オブジェクトID')),
                ('pv', models.PositiveIntegerField(default=0, verbose_name='ページビュー')),
                ('users', models.PositiveIntegerField(default=0, verbose_name='ユーザー数')),
                ('sessions', models.PositiveIntegerField(default=0, verbose_name='セッション数')),
                ('source_medium', models.CharField(max_length=255, verbose_name='参照元/メディア')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_analytics', to='community.community', verbose_name='集会')),
            ],
            options={
                'verbose_name': 'ページ解析',
                'verbose_name_plural': 'ページ解析',
                'db_table': 'page_analytics',
                'ordering': ['-date', '-pv'],
                'unique_together': {('page_path', 'date', 'source_medium')},
            },
        ),
    ]
