# Generated by Django 4.2.30 on 2026-06-01 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0025_alter_community_default_lt_duration'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageanalytics',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_analytics', to='community.community', verbose_name='集会'),
        ),
        migrations.AlterField(
            model_name='pageanalytics',
            name='content_type',
            field=models.CharField(choices=[('community', '集会ページ'), ('event_detail', 'イベント詳細ページ'), ('global', 'サイト全体（紐付けなし）')], max_length=20, verbose_name='コンテンツ種別'),
        ),
        migrations.AlterField(
            model_name='pageanalytics',
            name='object_id',
            field=models.PositiveIntegerField(default=0, verbose_name='オブジェクトID'),
        ),
        migrations.CreateModel(
            name='PosterClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日付')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='クリック数')),
                ('users', models.PositiveIntegerField(default=0, verbose_name='クリックユーザー数')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster_clicks', to='community.community', verbose_name='集会')),
            ],
            options={
                'verbose_name': 'ポスタークリック',
                'verbose_name_plural': 'ポスタークリック',
                'db_table': 'poster_click',
                'ordering': ['-date'],
                'unique_together': {('community', 'date')},
            },
        ),
    ]
