# Generated by Django 4.2.30 on 2026-06-02 01:43

import analytics.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0025_alter_community_default_lt_duration'),
        ('analytics', '0002_alter_pageanalytics_community_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pageanalytics',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pageanalytics',
            name='campaign',
            field=models.CharField(db_index=True, default='(not set)', max_length=128, verbose_name='キャンペーン'),
        ),
        migrations.AlterUniqueTogether(
            name='pageanalytics',
            unique_together={('page_path', 'date', 'source_medium', 'campaign')},
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: 技術書博 5/10 配布チラシ', max_length=100, verbose_name='表示名')),
                ('utm_source', models.CharField(help_text='流入元の媒体名。例: flyer / poster / twitter', max_length=64, verbose_name='utm_source')),
                ('utm_medium', models.CharField(default='qr', help_text='流入手段。QR コード経由なら qr のままで OK', max_length=64, verbose_name='utm_medium')),
                ('utm_campaign', models.SlugField(help_text='キャンペーン識別子。例: 20260510-gishohaku（半角英数とハイフン）', max_length=64, verbose_name='utm_campaign')),
                ('landing_path', models.CharField(default='/', help_text='例: / または /community/123/', max_length=255, verbose_name='着地パス')),
                ('qr_image', models.ImageField(blank=True, upload_to=analytics.models.qr_image_upload_to, verbose_name='QR画像')),
                ('distributed_at', models.DateField(blank=True, null=True, verbose_name='配布予定日')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='community.community', verbose_name='集会')),
            ],
            options={
                'verbose_name': 'キャンペーン',
                'verbose_name_plural': 'キャンペーン',
                'db_table': 'campaign',
                'ordering': ['-created_at'],
                'unique_together': {('community', 'utm_campaign')},
            },
        ),
    ]
