# Generated by Django 4.2.30 on 2026-06-02 02:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_pageanalytics_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='utm_medium',
            field=models.CharField(default='qr', help_text='流入手段。QR コード経由なら qr のままで OK（半角英数記号のみ）', max_length=64, validators=[django.core.validators.RegexValidator(message='半角英数とハイフン・アンダースコア・ドットのみ使用できます。', regex='^[A-Za-z0-9_.\\-]+$')], verbose_name='utm_medium'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='utm_source',
            field=models.CharField(help_text='流入元の媒体名。例: flyer / poster / twitter（半角英数記号のみ）', max_length=64, validators=[django.core.validators.RegexValidator(message='半角英数とハイフン・アンダースコア・ドットのみ使用できます。', regex='^[A-Za-z0-9_.\\-]+$')], verbose_name='utm_source'),
        ),
    ]
