# Generated by Django 4.2.30 on 2026-06-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_pageanalytics_content_type_add_campaign'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pageanalytics',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='posterclick',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pageanalytics',
            constraint=models.UniqueConstraint(fields=('page_path', 'date', 'source_medium', 'campaign'), name='pageanalytics_unique_path_date_source'),
        ),
        migrations.AddConstraint(
            model_name='posterclick',
            constraint=models.UniqueConstraint(fields=('community', 'date'), name='communityanalytics_unique_community_date'),
        ),
    ]
