# Generated by Django 4.2.30 on 2026-06-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_pageanalytics_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('community', 'utm_campaign'), name='campaign_unique_community_utm_campaign'),
        ),
    ]
