# Generated by Django 5.2.14 on 2026-07-14 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_alter_campaign_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='utm_medium',
            field=models.CharField(
                default='qr',
                help_text='流入手段。QR コード経由なら qr のままで OK（半角英数記号のみ）',
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        message='半角英数とハイフン・アンダースコア・ドットのみ使用できます。',
                        regex='\\A[A-Za-z0-9_.\\-]+\\Z',
                    ),
                ],
                verbose_name='utm_medium',
            ),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='utm_source',
            field=models.CharField(
                help_text='流入元の媒体名。例: flyer / poster / twitter（半角英数記号のみ）',
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        message='半角英数とハイフン・アンダースコア・ドットのみ使用できます。',
                        regex='\\A[A-Za-z0-9_.\\-]+\\Z',
                    ),
                ],
                verbose_name='utm_source',
            ),
        ),
    ]
