# Generated by Django 4.2.13 on 2024-06-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='contents',
            field=models.TextField(blank=True, default='', verbose_name='内容'),
        ),
    ]
