# Generated by Django 4.2.13 on 2024-06-05 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='materials_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='event',
            name='speakers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='event',
            name='youtube_url',
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('materials_url', models.URLField(blank=True, verbose_name='資料 URL')),
                ('speakers', models.CharField(max_length=200, verbose_name='登壇者')),
                ('theme', models.CharField(max_length=100, verbose_name='テーマ')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='event.event', verbose_name='イベント')),
            ],
            options={
                'verbose_name': 'イベント詳細',
                'verbose_name_plural': 'イベント詳細',
            },
        ),
    ]
