# Generated by Django 4.2.13 on 2024-06-05 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_event_materials_url_remove_event_overview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdetail',
            old_name='materials_url',
            new_name='slide_url',
        ),
    ]
