# Generated by Django 4.2.13 on 2024-06-18 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventdetail_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='event.event', verbose_name='イベント'),
        ),
    ]
