# Generated by Django 4.2.13 on 2024-06-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_materials_url_eventdetail_slide_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='slide_file',
            field=models.URLField(blank=True, verbose_name='スライド'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='slide_url',
            field=models.URLField(blank=True, verbose_name='スライド URL'),
        ),
    ]
