# Generated by Django 4.2.13 on 2024-06-05 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventdetail_slide_file_alter_eventdetail_slide_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdetail',
            old_name='speakers',
            new_name='speaker',
        ),
    ]
