# Generated by Django 4.2.13 on 2024-06-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventdetail_duration_eventdetail_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='h1',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='タイトル(H1)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=60, verbose_name='開催時間（分）'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='duration',
            field=models.IntegerField(default=30, verbose_name='発表時間（分）'),
        ),
    ]
