# Generated by Django 4.2.13 on 2024-06-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventdetail_h1_alter_event_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='start_time',
            field=models.TimeField(db_index=True, default='22:00', verbose_name='開始時刻'),
        ),
        migrations.AddIndex(
            model_name='eventdetail',
            index=models.Index(fields=['event', 'start_time'], name='event_detai_event_i_75f17d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdetail',
            index=models.Index(fields=['event', '-start_time'], name='event_detai_event_i_48ced6_idx'),
        ),
    ]
