# Generated by Django 4.2.13 on 2024-06-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_rename_speakers_eventdetail_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='speaker',
            field=models.CharField(max_length=200, verbose_name='発表者'),
        ),
    ]
