# Generated by Django 4.2.17 on 2025-01-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_eventdetail_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='meta_description',
            field=models.TextField(blank=True, default='', verbose_name='メタディスクリプション'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='speaker',
            field=models.CharField(blank=True, db_index=True, default='', help_text='VRChat表示名が望ましい。ただし、表記揺れはそのうち勝手に調整します', max_length=200, verbose_name='発表者'),
        ),
    ]
