# Generated by Django 4.2.13 on 2024-06-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_eventdetail_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='slide_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='スライド'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='slide_url',
            field=models.URLField(blank=True, null=True, verbose_name='スライド URL'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='speaker',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='発表者'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='テーマ'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube URL'),
        ),
    ]
