# Generated by Django 4.2.13 on 2024-06-05 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_eventdetail_slide_file_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventdetail',
            table='event_detail',
        ),
    ]
