# Generated by Django 4.2.17 on 2025-01-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_eventdetail_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='meta_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='メタディスクリプション'),
        ),
    ]
