# Generated by Django 4.2.17 on 2025-01-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_eventdetail_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GoogleカレンダーイベントID'),
        ),
    ]
