# Generated by Django 4.2.13 on 2024-06-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_eventdetail_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='speaker',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='発表者'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='theme',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='テーマ'),
        ),
    ]
