# Generated by Django 4.2.20 on 2025-06-01 12:53

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_event_google_calendar_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='slide_file',
            field=models.FileField(blank=True, null=True, upload_to='slide/', validators=[event.models.validate_pdf_file], verbose_name='スライド'),
        ),
    ]
