# Generated by Django 4.2.13 on 2024-06-08 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_eventdetail_speaker_alter_eventdetail_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='eventdetail',
            name='slide_file',
            field=models.FileField(blank=True, null=True, upload_to='slide/', verbose_name='スライド'),
        ),
    ]
