# Generated by Django 4.2.20 on 2025-06-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('event', '0010_add_pdf_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='detail_type',
            field=models.CharField(choices=[('LT', 'LT（発表）'), ('SPECIAL', '特別企画'), ('BLOG', 'ブログ')],
                                   db_index=True, default='LT', max_length=10, verbose_name='タイプ'),
        ),
        migrations.AddIndex(
            model_name='eventdetail',
            index=models.Index(fields=['detail_type'], name='event_detai_detail__570767_idx'),
        ),
    ]
