# Generated by Django 4.2.22 on 2025-06-20 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_eventdetail_detail_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('WEEKLY', '毎週'), ('MONTHLY_BY_DATE', '毎月（日付指定）'), ('MONTHLY_BY_WEEK', '毎月（第N曜日）'), ('OTHER', 'その他（自由記述）')], max_length=20, verbose_name='頻度')),
                ('interval', models.IntegerField(default=1, verbose_name='間隔')),
                ('week_of_month', models.IntegerField(blank=True, null=True, verbose_name='第N週')),
                ('custom_rule', models.TextField(blank=True, null=True, verbose_name='カスタムルール')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '定期ルール',
                'verbose_name_plural': '定期ルール',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='is_recurring_master',
            field=models.BooleanField(default=False, verbose_name='定期イベントの親'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurring_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='event.event', verbose_name='親イベント'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.recurrencerule', verbose_name='定期ルール'),
        ),
    ]
