# Generated by Django 4.2.13 on 2025-06-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_recurrencerule_event_is_recurring_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrencerule',
            name='start_date',
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name='起点日',
                help_text='定期イベントの起点となる日付。隔週の場合はこの日付を基準に計算されます。'
            ),
        ),
    ]