# Generated by Django 4.2.23 on 2025-06-20 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_community_allow_poster_repost'),
        ('event', '0015_add_start_date_to_recurrencerule'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrencerule',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='community.community', verbose_name='集会'),
        ),
    ]
