# Generated by Django 4.2.23 on 2025-06-20 15:35

from django.db import migrations


def populate_recurrencerule_community(apps, schema_editor):
    """既存のRecurrenceRuleにコミュニティを設定"""
    RecurrenceRule = apps.get_model('event', 'RecurrenceRule')
    Event = apps.get_model('event', 'Event')
    
    for rule in RecurrenceRule.objects.filter(community__isnull=True):
        # このルールに関連する最初のイベントからコミュニティを取得
        event = Event.objects.filter(recurrence_rule=rule).select_related('community').first()
        if event and event.community:
            rule.community = event.community
            rule.save()


def reverse_populate_recurrencerule_community(apps, schema_editor):
    """逆マイグレーション（communityをNullに戻す）"""
    RecurrenceRule = apps.get_model('event', 'RecurrenceRule')
    RecurrenceRule.objects.update(community=None)


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_add_community_to_recurrencerule'),
    ]

    operations = [
        migrations.RunPython(
            populate_recurrencerule_community,
            reverse_populate_recurrencerule_community
        ),
    ]
