# Generated by Django 4.2.27 on 2026-01-27 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0017_populate_recurrencerule_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accepts_lt_application',
            field=models.BooleanField(default=True, verbose_name='LT申し込み受付'),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lt_applications', to=settings.AUTH_USER_MODEL, verbose_name='申請者'),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='却下理由'),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='status',
            field=models.CharField(choices=[('pending', '承認待ち'), ('approved', '承認済み'), ('rejected', '却下')], db_index=True, default='approved', max_length=10, verbose_name='申請状態'),
        ),
    ]
