# Generated by Django 4.2.27 on 2026-01-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_event_accepts_lt_application_eventdetail_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='additional_info',
            field=models.TextField(blank=True, default='', help_text='登壇者が入力した追加情報', verbose_name='追加情報'),
        ),
    ]
