# Generated by Codex for issue #262

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_eventdetail_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='thumbnail_image',
            field=models.ImageField(
                blank=True,
                help_text='記事ページの上部に表示する画像',
                null=True,
                upload_to='thumbnail/',
                verbose_name='サムネイル画像',
            ),
        ),
    ]
