# Generated by Codex on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_eventdetail_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='event_thumbnail/', verbose_name='サムネイル画像'),
        ),
    ]
