# Generated by Django 4.2.30 on 2026-05-25 14:56

from django.db import migrations, models
import event.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_eventdetail_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='slide_file',
            field=models.FileField(blank=True, null=True, upload_to=event.models.slide_file_upload_to, validators=[event.models.validate_pdf_file], verbose_name='スライド'),
        ),
    ]
