# Generated by Django 4.2.30 on 2026-06-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_alter_eventdetail_slide_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('community', 'date', 'start_time'), name='event_unique_community_date_start_time'),
        ),
    ]
