# Generated by Codex on 2026-06-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0022_alter_event_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialUploadReminderLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "送信済み"), ("skipped_by_note", "備考で除外")],
                        db_index=True,
                        max_length=30,
                        verbose_name="状態",
                    ),
                ),
                ("reason", models.TextField(blank=True, default="", verbose_name="理由")),
                ("matched_intent", models.CharField(blank=True, default="", max_length=100, verbose_name="一致した意図")),
                ("confidence", models.CharField(blank=True, default="", max_length=20, verbose_name="信頼度")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="送信日時")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "event_detail",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_upload_reminder_log",
                        to="event.eventdetail",
                        verbose_name="イベント詳細",
                    ),
                ),
            ],
            options={
                "verbose_name": "発表資料アップロード依頼ログ",
                "verbose_name_plural": "発表資料アップロード依頼ログ",
                "db_table": "event_material_upload_reminder_log",
            },
        ),
    ]
