# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0023_material_upload_reminder_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialuploadreminderlog",
            name="follow_up_sent_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="1週間後リマインド送信日時",
            ),
        ),
    ]
