# Generated by Django 5.2.14 on 2026-06-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_materialuploadreminderlog_follow_up_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='detail_type',
            field=models.CharField(choices=[('LT', '発表'), ('SPECIAL', '特別企画'), ('BLOG', 'ブログ')], db_index=True, default='LT', max_length=10, verbose_name='タイプ'),
        ),
    ]
