# Generated by Django 5.2.14 on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_alter_eventdetail_detail_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrencerule',
            name='last_generated_date',
            field=models.DateField(
                blank=True,
                help_text='最後にイベント生成した日付（冪等性保証・進捗トラッキング用）',
                null=True,
                verbose_name='最終生成日',
            ),
        ),
    ]
