# Generated by Django 5.2.14 on 2026-07-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_eventdetail_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetail',
            name='duration',
            field=models.IntegerField(default=30, verbose_name='発表の持ち時間（分）'),
        ),
    ]
