# Generated by Django 5.2.14 on 2026-07-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0028_alter_community_default_lt_duration'),
        ('event', '0028_alter_eventdetail_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOccurrenceTombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='元の開催日')),
                ('original_start_time', models.TimeField(verbose_name='元の開始時刻')),
                ('reason', models.CharField(choices=[('deleted', '削除'), ('rescheduled', '日付移動')], max_length=16, verbose_name='理由')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_occurrence_tombstones', to='community.community', verbose_name='集会')),
            ],
            options={
                'db_table': 'event_occurrence_tombstone',
                'constraints': [models.UniqueConstraint(fields=('community', 'date'), name='event_tombstone_unique_community_date')],
            },
        ),
    ]
