# Generated by Django 5.2.14 on 2026-07-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_eventoccurrencetombstone'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='cached_transcript',
            field=models.TextField(blank=True, default='', help_text='YouTube字幕のキャッシュ（ブログ再生成時のAPI再取得防止）'),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='cached_transcript_video_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
