# Generated by Django 5.2.14 on 2026-09-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_eventdetail_cached_transcript_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='recording_policy',
            field=models.CharField(choices=[('forbidden', '禁止（撮影しない）'), ('allowed', '許可（撮影するが公開しない）'), ('public', '公開（撮影して YouTube で公開）')], db_default='public', default='public', max_length=20, verbose_name='撮影'),
        ),
    ]
