# Generated by Django 5.2.14 on 2026-10-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_backfill_recording_policy_from_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetail',
            name='article_body_hash',
            field=models.CharField(blank=True, db_default='', default='', max_length=64, verbose_name='記事の本文のハッシュ'),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='article_consent',
            field=models.CharField(choices=[('unanswered', '未回答'), ('ok', '記事化 OK（スライド画像の掲載を含む）'), ('ng', '記事化 NG')], db_default='unanswered', default='unanswered', max_length=16, verbose_name='記事化'),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='article_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='記事の生成日時'),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='article_generation_attempts',
            field=models.PositiveSmallIntegerField(db_default=0, default=0, verbose_name='記事の生成の試行回数'),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='article_generation_last_error',
            field=models.CharField(blank=True, db_default='', default='', max_length=255, verbose_name='記事の生成の最後のエラー'),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='article_generation_requested_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='記事の生成待ち'),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='article_source_slide_name',
            field=models.CharField(blank=True, db_default='', default='', max_length=255, verbose_name='記事の生成元の PDF'),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='article_source_video_id',
            field=models.CharField(blank=True, db_default='', default='', max_length=32, verbose_name='記事の生成元の動画 ID'),
        ),
    ]
