# Generated by Django 5.2.17 on 2026-10-08 02:28

import discord_scheduler.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledDiscordPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000, validators=[discord_scheduler.models.validate_discord_content], verbose_name='投稿本文')),
                ('scheduled_at', models.DateTimeField(verbose_name='投稿予定日時')),
                ('status', models.CharField(choices=[('scheduled', '予約済み'), ('sending', '送信中'), ('sent', '送信済み'), ('failed', '失敗'), ('needs_review', '要確認'), ('cancelled', '取消済み')], default='scheduled', max_length=20, verbose_name='状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='送信開始日時')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='送信日時')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='送信制限の解除予定日時')),
                ('message_url', models.URLField(blank=True, max_length=500, verbose_name='Discordの投稿URL')),
                ('error_message', models.TextField(blank=True, verbose_name='処理結果の補足')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_discord_posts', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'Discord予約投稿',
                'verbose_name_plural': 'Discord予約投稿',
                'ordering': ['scheduled_at', 'pk'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='discord_sched_due_idx')],
            },
        ),
    ]
