# Generated by Django 4.2.13 on 2024-07-17 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_community_is_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_condition', models.TextField(blank=True, default='', verbose_name='参加条件')),
                ('event_detail', models.TextField(blank=True, default='', verbose_name='イベント詳細')),
                ('how_to_join', models.TextField(blank=True, default='', verbose_name='参加方法')),
                ('note', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('is_overseas_user', models.BooleanField(default=False, verbose_name='海外ユーザー向け')),
                ('event_genres', models.JSONField(blank=True, default=list, verbose_name='イベントジャンル')),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entry', to='community.community')),
            ],
            options={
                'db_table': 'calendar_entry',
            },
        ),
    ]
