# Generated by Django 4.2.22 on 2025-06-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarentry',
            name='x_post_text',
            field=models.TextField(blank=True, default='', verbose_name='X告知文'),
        ),
    ]
