# Generated by Django 4.2.23 on 2025-08-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_update_categories_and_seed_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO用のメタディスクリプション（空欄の場合は本文から自動生成）'),
        ),
    ]
