# Generated by Django 4.2.13 on 2024-06-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('max_size', models.IntegerField(default=720)),
            ],
            options={
                'verbose_name': '画像ファイル',
                'verbose_name_plural': '画像ファイル',
            },
        ),
    ]
