# Generated by Django 4.2.13 on 2024-06-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='max_size',
            field=models.IntegerField(default=720),
        ),
    ]
