# Generated by Django 4.2.13 on 2024-06-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ta_hub', '0002_imagefile_max_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagefile',
            options={'verbose_name': '画像ファイル', 'verbose_name_plural': '画像ファイル'},
        ),
    ]
