# Generated by Django 4.2.13 on 2024-06-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='discord_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Discord ID'),
        ),
    ]
