# Generated by Django 4.2.20 on 2025-06-02 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='APIキー')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='キー名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='最終使用日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'APIキー',
                'verbose_name_plural': 'APIキー',
            },
        ),
    ]
