# Generated by Django 4.2.27 on 2026-01-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_apikey'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='apikey',
            table='account_apikey',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='account_customuser',
        ),
    ]
