# Generated by Django 4.2.27 on 2026-01-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_alter_apikey_table_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(error_messages={'unique': 'そのユーザー名はすでに使用されています。'}, help_text='必須。150文字以下。文字、数字、@/./+/-/_のみ使用可能です。', max_length=150, unique=True, verbose_name='ユーザー名'),
        ),
    ]
