# Generated by Django 4.2.27 on 2026-01-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_alter_customuser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='必須。有効なメールアドレスを入力してください。', max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
    ]
