# Generated by Django 4.2.27 on 2026-01-31 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_add_unique_to_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='discord_id',
        ),
    ]
