# Generated by Codex on 2026-02-04

import hashlib
import re

from django.db import migrations


HEX64_RE = re.compile(r"^[0-9a-f]{64}$")


def hash_existing_api_keys(apps, schema_editor):
    """既存の平文APIキーをSHA-256（hex）に変換する."""
    APIKey = apps.get_model("user_account", "APIKey")

    for api_key in APIKey.objects.all().only("id", "key"):
        if not api_key.key:
            continue
        # 既にhex(64)の場合はハッシュ済みとみなす
        if HEX64_RE.match(api_key.key):
            continue
        api_key.key = hashlib.sha256(api_key.key.encode("utf-8")).hexdigest()
        api_key.save(update_fields=["key"])


class Migration(migrations.Migration):

    dependencies = [
        ("user_account", "0008_remove_discord_id"),
    ]

    operations = [
        migrations.RunPython(hash_existing_api_keys, migrations.RunPython.noop),
    ]

