# Generated by Django 4.2.30 on 2026-04-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0009_hash_apikeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vrchat_user_id',
            field=models.CharField(blank=True, default='', help_text='プロフィールURLまたはユーザーIDを入力できます。保存時にIDへ正規化されます。', max_length=64, verbose_name='VRChatユーザーID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='x_id',
            field=models.CharField(blank=True, default='', help_text='プロフィールURLまたはIDを入力できます。保存時にIDへ正規化されます。', max_length=15, verbose_name='X（Twitter）ID'),
        ),
    ]
