# Generated by Django 4.2.30 on 2026-05-26 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0009_hash_apikeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='x_account',
            field=models.CharField(blank=True, default='', help_text='@ なしのハンドル名（例: noricha_vr）。英数字とアンダースコア、1〜15文字。', max_length=15, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]{1,15}\\Z', 'X のハンドル名は英数字とアンダースコアで1〜15文字です。')], verbose_name='X (Twitter) アカウント'),
        ),
    ]
