# Generated by Django 4.2.30 on 2026-05-27 03:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0010_customuser_x_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vrchat_user_id',
            field=models.CharField(blank=True, default='', help_text='VRChatのユーザーID（usr_から始まるID）を保存します。', max_length=40, validators=[django.core.validators.RegexValidator('^usr_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\Z', 'VRChatユーザーIDは usr_ から始まるIDです。', flags=0)], verbose_name='VRChatユーザーID'),
        ),
    ]
