# Generated by Codex on 2026-06-05

from django.db import migrations, models


def copy_user_name_to_display_name(apps, schema_editor):
    CustomUser = apps.get_model('user_account', 'CustomUser')
    CustomUser.objects.filter(display_name='').update(display_name=models.F('user_name'))


def clear_display_name(apps, schema_editor):
    CustomUser = apps.get_model('user_account', 'CustomUser')
    CustomUser.objects.update(display_name='')


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0011_customuser_vrchat_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(
                blank=True,
                default='',
                help_text='VRChat等で使う表示名。同じ表示名を複数ユーザーが使用できます。',
                max_length=200,
                verbose_name='表示名',
            ),
        ),
        migrations.RunPython(copy_user_name_to_display_name, clear_display_name),
    ]
