# Generated by Django 5.2.14 on 2026-06-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0012_customuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='allowed_ips',
            field=models.TextField(blank=True, default='', help_text='カンマ区切りで IP アドレスまたは CIDR を指定。空ならすべての IP を許可。', verbose_name='許可IP'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='有効期限'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='scope',
            field=models.CharField(choices=[('read', '読み取りのみ'), ('write', '読み書き')], default='write', max_length=16, verbose_name='権限スコープ'),
        ),
    ]
