# Generated by Django 5.2.14 on 2026-08-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0013_apikey_allowed_ips_apikey_expires_at_apikey_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(help_text='必須。150文字以下。文字、数字、@/./+/-/_のみ使用可能です。同じユーザー名を複数ユーザーが使用できます。', max_length=150, verbose_name='ユーザー名'),
        ),
    ]
