# Generated by Django 5.2.17 on 2026-10-07 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Exact-match collation for the ownership key on MySQL.
EXACT_MATCH_COLUMN_SQL = (
    'ALTER TABLE `user_account_emailownership` '
    'MODIFY `email` varchar(254) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL'
)


def use_exact_match_collation_on_mysql(apps, schema_editor):
    """Compare ownership keys exactly on MySQL, as Python does.

    Keys are already stripped and lower-cased (normalize_email_key), so a
    binary collation makes the unique index agree with the audit and the
    backfill. The default *_ai_ci collations also treat accented letters as
    equal. The model state keeps no collation because SQLite does not know
    utf8mb4_bin.
    """
    if schema_editor.connection.vendor != 'mysql':
        return
    schema_editor.execute(EXACT_MATCH_COLUMN_SQL)


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0016_login_rate_limit_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス（小文字）')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_ownerships', to=settings.AUTH_USER_MODEL, verbose_name='持ち主')),
            ],
            options={
                'verbose_name': 'メールアドレスの持ち主',
                'verbose_name_plural': 'メールアドレスの持ち主',
            },
        ),
        # Not atomic: on MySQL, Django wraps RunPython in a transaction and refuses DDL inside it.
        migrations.RunPython(use_exact_match_collation_on_mysql, migrations.RunPython.noop, atomic=False),
    ]
