# Generated by Django 5.2.17 on 2026-10-07 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0016_login_rate_limit_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス（小文字）')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_ownerships', to=settings.AUTH_USER_MODEL, verbose_name='持ち主')),
            ],
            options={
                'verbose_name': 'メールアドレスの持ち主',
                'verbose_name_plural': 'メールアドレスの持ち主',
            },
        ),
    ]
