# Generated by Django 4.2.28 on 2026-02-09 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0018_remove_lt_application_min_length'),
        ('event', '0019_eventdetail_additional_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='VketCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='コラボ名')),
                ('period_start', models.DateField(verbose_name='開催期間 開始')),
                ('period_end', models.DateField(verbose_name='開催期間 終了')),
                ('registration_deadline', models.DateField(verbose_name='参加表明締切（Step 1）')),
                ('lt_deadline', models.DateField(verbose_name='LT情報締切（Step 2）')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('open', '受付中'), ('closed', '受付終了'), ('archived', 'アーカイブ')], db_index=True, default='draft', max_length=20, verbose_name='状態')),
                ('hashtags', models.JSONField(blank=True, default=list, verbose_name='ハッシュタグ')),
                ('description', models.TextField(blank=True, verbose_name='案内文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'Vketコラボ',
                'verbose_name_plural': 'Vketコラボ',
                'db_table': 'vket_collaboration',
                'ordering': ['-period_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VketParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='備考（主催者）')),
                ('admin_note', models.TextField(blank=True, verbose_name='備考（運営）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='vket.vketcollaboration', verbose_name='コラボ')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vket_participations', to='community.community', verbose_name='集会')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vket_participations', to='event.event', verbose_name='参加イベント')),
            ],
            options={
                'verbose_name': 'Vket参加',
                'verbose_name_plural': 'Vket参加',
                'db_table': 'vket_participation',
            },
        ),
        migrations.AddConstraint(
            model_name='vketparticipation',
            constraint=models.UniqueConstraint(fields=('collaboration', 'community'), name='unique_vket_participation_per_community'),
        ),
    ]
