# Generated by Django 4.2.28 on 2026-03-06 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0020_alter_community_notification_webhook_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0019_eventdetail_additional_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='VketCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='スラッグ')),
                ('name', models.CharField(max_length=200, verbose_name='コラボ名')),
                ('phase', models.CharField(choices=[('draft', '下書き'), ('entry_open', '参加受付中'), ('scheduling', '日程調整中'), ('lt_collection', 'LT情報回収中'), ('announcement', '告知確認中'), ('locked', '確定'), ('archived', 'アーカイブ')], db_index=True, default='draft', max_length=20, verbose_name='フェーズ')),
                ('period_start', models.DateField(verbose_name='開催期間 開始')),
                ('period_end', models.DateField(verbose_name='開催期間 終了')),
                ('registration_deadline', models.DateField(verbose_name='参加表明締切（Step 1）')),
                ('lt_deadline', models.DateField(verbose_name='LT情報締切（Step 2）')),
                ('hashtags', models.JSONField(blank=True, default=list, verbose_name='ハッシュタグ')),
                ('description', models.TextField(blank=True, verbose_name='案内文')),
                ('settings_json', models.JSONField(blank=True, null=True, verbose_name='設定（JSON）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'Vketコラボ',
                'verbose_name_plural': 'Vketコラボ',
                'db_table': 'vket_collaboration',
                'ordering': ['-period_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VketNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('requires_ack', models.BooleanField(default=False, verbose_name='確認必須')),
                ('target_scope', models.CharField(choices=[('all', '全参加者'), ('unacked', '未確認者のみ'), ('manual', '手動選択')], default='all', max_length=20, verbose_name='配信対象')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='送信日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='vket.vketcollaboration', verbose_name='コラボ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vket_notices', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'Vketお知らせ',
                'verbose_name_plural': 'Vketお知らせ',
                'db_table': 'vket_notice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VketParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifecycle', models.CharField(choices=[('active', '参加中'), ('declined', '不参加'), ('withdrawn', '辞退')], db_index=True, default='active', max_length=20, verbose_name='参加状態')),
                ('progress', models.CharField(choices=[('not_applied', '未申請'), ('applied', '申請済み'), ('schedule_confirmed', '日程確定'), ('lt_pending', 'LT情報待ち'), ('lt_submitted', 'LT提出済み'), ('done', '完了')], db_index=True, default='not_applied', max_length=30, verbose_name='進捗')),
                ('requested_date', models.DateField(blank=True, null=True, verbose_name='希望日程')),
                ('requested_start_time', models.TimeField(blank=True, null=True, verbose_name='希望開始時刻')),
                ('requested_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='希望開催時間（分）')),
                ('confirmed_date', models.DateField(blank=True, null=True, verbose_name='確定日程')),
                ('confirmed_start_time', models.TimeField(blank=True, null=True, verbose_name='確定開始時刻')),
                ('confirmed_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='確定開催時間（分）')),
                ('schedule_adjusted_by_admin', models.BooleanField(default=False, verbose_name='管理者が日程調整済み')),
                ('organizer_note', models.TextField(blank=True, verbose_name='備考（主催者）')),
                ('admin_note', models.TextField(blank=True, verbose_name='備考（運営）')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='申請日時')),
                ('schedule_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='日程確定日時')),
                ('lt_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='LT提出日時')),
                ('last_acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='最終確認日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vket_applications', to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
                ('collaboration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='vket.vketcollaboration', verbose_name='コラボ')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vket_participations', to='community.community', verbose_name='集会')),
                ('last_acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vket_acknowledgements', to=settings.AUTH_USER_MODEL, verbose_name='最終確認者')),
                ('published_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vket_participations', to='event.event', verbose_name='公開イベント')),
            ],
            options={
                'verbose_name': 'Vket参加',
                'verbose_name_plural': 'Vket参加',
                'db_table': 'vket_participation',
            },
        ),
        migrations.CreateModel(
            name='VketPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('speaker', models.CharField(blank=True, max_length=200, verbose_name='登壇者名')),
                ('theme', models.CharField(blank=True, max_length=200, verbose_name='テーマ')),
                ('confirmed_start_time', models.TimeField(blank=True, null=True, verbose_name='確定開始時刻')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='発表時間（分）')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('submitted', '提出済み'), ('confirmed', '確定')], db_index=True, default='draft', max_length=20, verbose_name='状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='vket.vketparticipation', verbose_name='参加')),
                ('published_event_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vket_presentations', to='event.eventdetail', verbose_name='公開イベント詳細')),
            ],
            options={
                'verbose_name': 'Vketプレゼンテーション',
                'verbose_name_plural': 'Vketプレゼンテーション',
                'db_table': 'vket_presentation',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VketNoticeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='確認日時')),
                ('ack_token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='確認トークン')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vket_acks', to=settings.AUTH_USER_MODEL, verbose_name='確認者')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='vket.vketnotice', verbose_name='お知らせ')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_receipts', to='vket.vketparticipation', verbose_name='参加')),
            ],
            options={
                'verbose_name': 'Vket通知受信記録',
                'verbose_name_plural': 'Vket通知受信記録',
                'db_table': 'vket_notice_receipt',
            },
        ),
        migrations.AddConstraint(
            model_name='vketparticipation',
            constraint=models.UniqueConstraint(fields=('collaboration', 'community'), name='unique_vket_participation_per_community'),
        ),
        migrations.AddConstraint(
            model_name='vketnoticereceipt',
            constraint=models.UniqueConstraint(fields=('notice', 'participation'), name='unique_vket_notice_receipt'),
        ),
    ]
