# Generated by Django 4.2.28 on 2026-03-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vketpresentation',
            name='requested_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='希望開始時刻'),
        ),
    ]
