# Generated by Django 4.2.28 on 2026-03-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vket', '0002_vketpresentation_requested_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vketparticipation',
            name='stage_registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ステージ登録日時'),
        ),
        migrations.AlterField(
            model_name='vketparticipation',
            name='progress',
            field=models.CharField(choices=[('not_applied', '未申請'), ('applied', '申請済み'), ('schedule_confirmed', '日程確定'), ('stage_registered', 'ステージ登録済'), ('lt_pending', 'LT情報待ち'), ('lt_submitted', 'LT提出済み'), ('done', '完了')], db_index=True, default='not_applied', max_length=30, verbose_name='進捗'),
        ),
    ]
