# Generated by Django 4.2.28 on 2026-03-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vket', '0003_vketparticipation_stage_registered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vketparticipation',
            name='progress',
            field=models.CharField(choices=[('not_applied', '未申請'), ('applied', '申請済み'), ('stage_registered', 'ステージ登録済'), ('rehearsal', 'リハーサル'), ('event_week', '技術学術ウィーク'), ('after_party', '感想会'), ('done', '完了')], db_index=True, default='not_applied', max_length=30, verbose_name='進捗'),
        ),
    ]
