# Generated by Django 4.2.28 on 2026-04-05

from django.db import migrations


def _column_names(schema_editor, table_name: str) -> set[str]:
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(
            cursor, table_name
        )
    return {column.name for column in description}


def add_stage_registered_at_column_if_missing(apps, schema_editor):
    participation = apps.get_model("vket", "VketParticipation")
    table_name = participation._meta.db_table
    column_name = "stage_registered_at"

    # 0003 が適用済み扱いでも実カラム欠損の本番DBを復旧できるようにする。参照: PR #171（migration履歴と実スキーマのズレを自己修復するため）
    if column_name in _column_names(schema_editor, table_name):
        return

    field = participation._meta.get_field(column_name)
    table_sql = schema_editor.quote_name(table_name)
    column_sql = schema_editor.quote_name(column_name)
    column_type = field.db_type(schema_editor.connection)
    schema_editor.execute(
        f"ALTER TABLE {table_sql} ADD COLUMN {column_sql} {column_type} NULL"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("vket", "0006_alter_vketparticipation_progress"),
    ]

    operations = [
        migrations.RunPython(
            add_stage_registered_at_column_if_missing,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
