# Generated by Django 4.2.30 on 2026-05-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vket', '0008_recheck_stage_registered_at_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vketcollaboration',
            name='lt_deadline',
            field=models.DateField(verbose_name='発表情報締切（Step 2）'),
        ),
        migrations.AlterField(
            model_name='vketcollaboration',
            name='phase',
            field=models.CharField(choices=[('draft', '下書き'), ('entry_open', '参加受付中'), ('scheduling', '日程調整中'), ('lt_collection', '発表情報回収中'), ('announcement', '告知確認中'), ('locked', '確定'), ('archived', 'アーカイブ')], db_index=True, default='draft', max_length=20, verbose_name='フェーズ'),
        ),
        migrations.AlterField(
            model_name='vketparticipation',
            name='lt_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='発表提出日時'),
        ),
        migrations.AlterField(
            model_name='vketparticipation',
            name='progress',
            field=models.CharField(choices=[('not_applied', '未申請'), ('applied', '申請済み'), ('stage_registered', 'ステージ登録済'), ('lt_registered', '発表登録済み'), ('rehearsal', 'リハーサル'), ('event_week', '技術学術WEEK'), ('lt_material_uploaded', '発表資料アップロード'), ('after_party', '感想会'), ('done', '完了')], db_index=True, default='not_applied', max_length=30, verbose_name='進捗'),
        ),
        migrations.AlterField(
            model_name='vketpresentation',
            name='status',
            field=models.CharField(choices=[('draft', '申請中'), ('submitted', '提出済み'), ('confirmed', '確定')], db_index=True, default='draft', max_length=20, verbose_name='状態'),
        ),
    ]
