# Generated by Django 5.2.14 on 2026-07-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vket', '0010_backfill_vket_event_detail_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='vketparticipation',
            name='lt_slot_minutes',
            field=models.PositiveIntegerField(default=30, help_text='発表と質疑応答を含む1人あたりの時間枠です。', verbose_name='1人あたり持ち時間（分）'),
        ),
    ]
