# Generated by Django 5.2.14 on 2026-07-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vket', '0011_vketparticipation_lt_slot_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vketpresentation',
            name='duration',
            field=models.PositiveIntegerField(default=30, verbose_name='発表の持ち時間（分）'),
        ),
    ]
