#!/usr/bin/env python3
"""Python 依存の入力（*.in）とロック（*.txt）の配置と版の一致を検証する。

Dependabot（uv エコシステム）は `requirements.in` → `requirements.txt`（uv pip compile の出力）の組だけを
理解し、両方を書き換える。ロックを `.lock` などの別名に戻すと、Dependabot は入力だけを上げ、
本番と CI は古い版を入れたまま緑になる。人が `.in` だけを直してロックし忘れた時もここで落とす。
"""

from __future__ import annotations

import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
# 入力 → ロック の組（本体と E2E）
PAIRS = (("requirements.in", "requirements.txt"), ("requirements-e2e.in", "requirements-e2e.txt"))
# `name[extra]==1.2.3` の完全固定だけを照合する（範囲指定はロック側の版が決める）
EXACT_PIN = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)(?:\[[^\]]*\])?==([0-9][^\s;*#\\]*)\s*(?:[;#\\].*)?$")


def normalize(name: str) -> str:
    """PEP 503 の正規化（大文字小文字と区切り文字の違いを吸収する）。"""
    return re.sub(r"[-_.]+", "-", name).lower()


def requirement_lines(path: Path) -> list[str]:
    """入力ファイルの要件行（コメント・空行・`-r` / `-c` などのオプション行を除く）。"""
    lines = [line.split(" #", 1)[0].strip() for line in path.read_text(encoding="utf-8").splitlines()]
    return [line for line in lines if line and not line.startswith(("#", "-"))]


def exact_pins(path: Path) -> dict[str, str]:
    """ファイル中の完全固定の pin を {正規化した名前: 版} で返す。"""
    pins: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = EXACT_PIN.match(line.strip())
        if match:
            pins[normalize(match.group(1))] = match.group(2)
    return pins


class RequirementsLayoutTest(unittest.TestCase):
    def test_locks_are_compiled_txt_files(self):
        self.assertEqual(sorted(p.name for p in ROOT.glob("requirements*.lock")), [])
        for source, lock in PAIRS:
            header = (ROOT / lock).read_text(encoding="utf-8").splitlines()[:2]
            self.assertTrue(header[0].startswith("# This file was autogenerated by uv"), lock)
            self.assertIn(source, header[1], lock)

    def test_e2e_input_includes_main_input_and_lock(self):
        # -r で Dependabot が本体を先にコンパイルし、-c で更新後の本体ロックに揃える
        lines = (ROOT / "requirements-e2e.in").read_text(encoding="utf-8").splitlines()
        self.assertIn("-r requirements.in", lines)
        self.assertIn("-c requirements.txt", lines)

    def test_e2e_lock_matches_main_lock_for_shared_packages(self):
        main = exact_pins(ROOT / "requirements.txt")
        e2e = exact_pins(ROOT / "requirements-e2e.txt")
        self.assertEqual({n: (v, e2e[n]) for n, v in main.items() if n in e2e and e2e[n] != v}, {})
        self.assertEqual(sorted(set(main) - set(e2e)), [], "E2E のロックは本体の依存をすべて含む")

    def test_inputs_pin_every_requirement_exactly(self):
        # 範囲指定はロックとの照合で見逃すため、入力は == の完全固定に限る（README の規約）
        for source, _ in PAIRS:
            loose = [line for line in requirement_lines(ROOT / source) if not EXACT_PIN.match(line)]
            self.assertEqual(loose, [], f"{source} に == で固定していない要件がある")

    def test_dockerfile_installs_the_lock(self):
        source = (ROOT / "Dockerfile").read_text(encoding="utf-8")
        self.assertIn("pip3 install --no-deps -r /app/requirements.txt", source)
        self.assertNotIn("requirements.lock", source)

    def test_every_exact_pin_in_input_matches_the_lock(self):
        for source, lock in PAIRS:
            wanted = exact_pins(ROOT / source)
            locked = exact_pins(ROOT / lock)
            self.assertTrue(wanted, f"{source} から pin を読めない")
            mismatched = {n: (v, locked.get(n)) for n, v in wanted.items() if locked.get(n) != v}
            self.assertEqual(
                mismatched, {}, f"{source} と {lock} の版が違う（.in を直した後に uv pip compile し直していない？）"
            )

    def test_exact_pin_parser_handles_extras_and_skips_ranges(self):
        self.assertEqual(EXACT_PIN.match("django-allauth[socialaccount]==65.19.7").group(2), "65.19.7")
        self.assertEqual(EXACT_PIN.match("qrcode[pil]==8.0").group(2), "8.0")
        self.assertIsNone(EXACT_PIN.match("django==5.2.*"))
        self.assertIsNone(EXACT_PIN.match("google-auth>=2.14.1,<3.0.0"))
        self.assertIsNone(EXACT_PIN.match("-c requirements.txt"))
        self.assertEqual(normalize("django_filter"), "django-filter")


if __name__ == "__main__":
    unittest.main()
