# Generated by Django 5.2.14 on 2026-07-20 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account', '0013_apikey_allowed_ips_apikey_expires_at_apikey_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_method', models.CharField(choices=[('anonymous', '未認証'), ('session', 'セッション'), ('api_key', 'APIキー')], default='anonymous', max_length=16)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=8)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('remote_ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='user_account.apikey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['-created_at'], name='api_v1_apir_created_5573e0_idx'), models.Index(fields=['user', '-created_at'], name='api_v1_apir_user_id_30c05b_idx'), models.Index(fields=['api_key', '-created_at'], name='api_v1_apir_api_key_e95d18_idx')],
            },
        ),
    ]
