# Generated by Django 5.2.14 on 2026-10-09 05:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='本文')),
                ('scheduled_at', models.DateTimeField(verbose_name='送信日時')),
                ('mention_everyone_confirmed', models.BooleanField(default=False, help_text='本文の @everyone / @here で全員に通知することを、保存した人が確認したか', verbose_name='全員への通知を確認済み')),
                ('status', models.CharField(choices=[('scheduled', '予約中'), ('sent', '送信済み'), ('failed', '失敗'), ('canceled', '取り消し')], default='scheduled', max_length=16, verbose_name='状態')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, verbose_name='送信を試みた回数')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='次に送信を試みる日時')),
                ('lease_token', models.CharField(blank=True, default='', max_length=32, verbose_name='送信処理のリース')),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='リースの期限')),
                ('last_error', models.CharField(blank=True, default='', max_length=500, verbose_name='エラーの要約')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='送信した日時')),
                ('discord_message_id', models.CharField(blank=True, default='', max_length=32, verbose_name='Discord のメッセージ ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': 'Discord 告知の予約送信',
                'verbose_name_plural': 'Discord 告知の予約送信',
                'db_table': 'discord_scheduled_message',
                'ordering': ['-scheduled_at', '-pk'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='discord_msg_status_sched_idx')],
            },
        ),
    ]
