# Generated by Django 4.2.13 on 2024-07-18 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_community_is_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Twitter Template', max_length=255, verbose_name='テンプレート名')),
                ('template', models.TextField(help_text='利用可能な変数: {event_name}, {date}, {time}, {speaker}, {theme}', verbose_name='テンプレート')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_template', to='community.community')),
            ],
            options={
                'db_table': 'twitter_template',
            },
        ),
    ]
