# Generated by Django 4.2.14 on 2024-07-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittertemplate',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='テンプレート名'),
        ),
    ]
