# Generated by Django 4.2.29 on 2026-04-03 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_eventdetail_additional_info'),
        ('community', '0022_alter_community_poster_image'),
        ('twitter', '0002_alter_twittertemplate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_type', models.CharField(choices=[('new_community', '新規集会'), ('lt', 'LT告知'), ('special', '特別回告知')], max_length=20, verbose_name='種別')),
                ('generated_text', models.TextField(blank=True, verbose_name='生成テキスト')),
                ('status', models.CharField(choices=[('pending', '投稿待ち'), ('posted', '投稿済み'), ('failed', '失敗')], default='pending', max_length=10, verbose_name='状態')),
                ('tweet_id', models.CharField(blank=True, max_length=50, verbose_name='ツイートID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='投稿日時')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet_queues', to='community.community')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweet_queues', to='event.event')),
                ('event_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweet_queues', to='event.eventdetail')),
            ],
            options={
                'verbose_name': 'ツイートキュー',
                'verbose_name_plural': 'ツイートキュー',
                'db_table': 'tweet_queue',
                'ordering': ['-created_at'],
            },
        ),
    ]
