# Generated by Django 4.2.29 on 2026-04-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_tweetqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='XApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='アクセストークン')),
                ('refresh_token', models.TextField(verbose_name='リフレッシュトークン')),
                ('expires_at', models.DateTimeField(verbose_name='有効期限')),
                ('screen_name', models.CharField(blank=True, max_length=100, verbose_name='アカウント名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'X APIトークン',
                'verbose_name_plural': 'X APIトークン',
                'db_table': 'x_api_token',
            },
        ),
    ]
