# Generated by Django 4.2.29 on 2026-04-04 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_xapitoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XApiToken',
        ),
    ]
