# Generated by Django 4.2.29 on 2026-04-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_delete_xapitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetqueue',
            name='image_url',
            field=models.URLField(blank=True, help_text='投稿に添付する画像のURL（R2等）', verbose_name='画像URL'),
        ),
        migrations.AlterField(
            model_name='tweetqueue',
            name='status',
            field=models.CharField(choices=[('generating', '生成中'), ('generation_failed', '生成失敗'), ('ready', '投稿待ち'), ('posted', '投稿済み'), ('failed', '投稿失敗')], default='generating', max_length=20, verbose_name='状態'),
        ),
    ]
