# Generated by Django 4.2.29 on 2026-04-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_tweetqueue_image_url_alter_tweetqueue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetqueue',
            name='tweet_type',
            field=models.CharField(choices=[('new_community', '新規集会'), ('lt', 'LT告知'), ('special', '特別回告知'), ('slide_share', 'スライド/記事共有')], max_length=20, verbose_name='種別'),
        ),
    ]
