# Generated by Django 4.2.29 on 2026-04-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_alter_tweetqueue_tweet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetqueue',
            name='tweet_type',
            field=models.CharField(choices=[('new_community', '新規集会'), ('lt', 'LT告知'), ('special', '特別回告知'), ('daily_reminder', '当日リマインド'), ('slide_share', 'スライド/記事共有')], max_length=20, verbose_name='種別'),
        ),
        migrations.AddConstraint(
            model_name='tweetqueue',
            constraint=models.UniqueConstraint(condition=models.Q(('tweet_type', 'daily_reminder')), fields=('event', 'tweet_type'), name='unique_daily_reminder_per_event'),
        ),
    ]
