# Generated by Django 4.2.29 on 2026-04-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_alter_tweetqueue_tweet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetqueue',
            name='status',
            field=models.CharField(choices=[('generating', '生成中'), ('generation_failed', '生成失敗'), ('ready', '投稿待ち'), ('posted', '投稿済み'), ('skipped', 'スキップ'), ('failed', '投稿失敗')], default='generating', max_length=20, verbose_name='状態'),
        ),
    ]
