# Generated by Django 4.2.29 on 2026-04-17 03:10

from datetime import datetime, time, timedelta, timezone as dt_timezone
from zoneinfo import ZoneInfo

from django.db import migrations, models


JST = ZoneInfo("Asia/Tokyo")


def _scheduled_at_for_date(target_date):
    return datetime.combine(target_date, time(hour=19), tzinfo=JST).astimezone(dt_timezone.utc)


def _default_scheduled_at(tweet_type, event_date, created_at):
    if tweet_type == 'daily_reminder' and event_date is not None:
        return _scheduled_at_for_date(event_date)

    if created_at is None:
        created_at = datetime.now(dt_timezone.utc)

    local_created = created_at.astimezone(JST)
    scheduled = _scheduled_at_for_date(local_created.date())
    if local_created >= scheduled.astimezone(JST):
        scheduled += timedelta(days=1)
    return scheduled


def backfill_scheduled_at(apps, schema_editor):
    TweetQueue = apps.get_model('twitter', 'TweetQueue')

    for queue in TweetQueue.objects.select_related('event').all():
        event_date = queue.event.date if queue.event_id and queue.event else None
        queue.scheduled_at = _default_scheduled_at(
            tweet_type=queue.tweet_type,
            event_date=event_date,
            created_at=queue.created_at,
        )
        queue.save(update_fields=['scheduled_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0009_alter_tweetqueue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetqueue',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='予約日時'),
        ),
        migrations.RunPython(backfill_scheduled_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='tweetqueue',
            name='scheduled_at',
            field=models.DateTimeField(verbose_name='予約日時'),
        ),
    ]
