# Generated by Django 4.2.30 on 2026-05-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0010_tweetqueue_scheduled_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweetqueue',
            options={'ordering': ['-created_at'], 'verbose_name': 'ポストキュー', 'verbose_name_plural': 'ポストキュー'},
        ),
        migrations.AlterField(
            model_name='tweetqueue',
            name='tweet_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='ポストID'),
        ),
        migrations.AlterField(
            model_name='tweetqueue',
            name='tweet_type',
            field=models.CharField(choices=[('new_community', '新規集会'), ('lt', '発表告知'), ('special', '特別回告知'), ('daily_reminder', '当日リマインド'), ('slide_share', 'スライド/記事共有')], max_length=20, verbose_name='種別'),
        ),
    ]
