# Generated by Codex on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0011_alter_tweetqueue_options_alter_tweetqueue_tweet_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetqueue',
            name='generation_token',
            field=models.CharField(blank=True, max_length=32, verbose_name='生成トークン'),
        ),
    ]
