# Generated by Django 4.2.13 on 2024-06-13 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False,
                                                     help_text='Designates that this custom_user has all permissions without explicitly assigning them.',
                                                     verbose_name='superuser status')),
                ('user_name', models.CharField(error_messages={'unique': 'その集会名はすでに使用されています。'},
                                               help_text='必須。150文字以下。文字、数字、@/./+/-/_のみ使用可能です。',
                                               max_length=150, unique=True, verbose_name='集会名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス')),
                ('is_staff', models.BooleanField(default=False,
                                                 help_text='このユーザーが管理サイトにログインできるかどうかを指定します。',
                                                 verbose_name='スタッフ権限')),
                ('is_active', models.BooleanField(default=True,
                                                  help_text='このユーザーを有効として扱うかどうかを指定します。無効にする代わりに、これを選択解除してください。',
                                                  verbose_name='有効')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon/', verbose_name='アイコン')),
                ('groups', models.ManyToManyField(blank=True,
                                                  help_text='The groups this custom_user belongs to. A custom_user will get all permissions granted to each of their groups.',
                                                  related_name='customuser_set', to='auth.group',
                                                  verbose_name='groups')),
                ('user_permissions',
                 models.ManyToManyField(blank=True, help_text='Specific permissions for this custom_user.',
                                        related_name='customuser_set', to='auth.permission',
                                        verbose_name='custom_user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
            },
        ),
    ]
