# Generated by Django 4.2.20 on 2025-04-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_discord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='必須。有効なメールアドレスを入力してください。', max_length=254, verbose_name='メールアドレス'),
        ),
    ]
