# Generated by Django 4.2.13 on 2024-06-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='イベント名')),
                ('start_from', models.DateField(blank=True, default=None, null=True, verbose_name='イベント開始日')),
                ('end_at', models.DateField(blank=True, default=None, null=True, verbose_name='イベント終了日')),
                ('start_time', models.TimeField(default='22:00', verbose_name='開始時刻')),
                ('duration', models.IntegerField(default=60, help_text='単位は分', verbose_name='開催時間')),
                ('weekday', models.CharField(choices=[('Sun', '日曜日'), ('Mon', '月曜日'), ('Tue', '火曜日'), ('Wed', '水曜日'), ('Thu', '木曜日'), ('Fri', '金曜日'), ('Sat', '土曜日'), ('Other', 'その他')], max_length=5, verbose_name='曜日')),
                ('frequency', models.CharField(max_length=100, verbose_name='開催周期')),
                ('organizers', models.CharField(max_length=200, verbose_name='主催・副主催')),
                ('group_url', models.URLField(blank=True, verbose_name='VRChatグループURL')),
                ('organizer_url', models.URLField(blank=True, verbose_name='VRChat主催プロフィールURL')),
                ('discord', models.URLField(blank=True, verbose_name='Discord')),
                ('twitter_hashtag', models.CharField(blank=True, max_length=100, verbose_name='Twitterハッシュタグ')),
                ('poster_image', models.ImageField(blank=True, upload_to='poster/', verbose_name='ポスター')),
                ('description', models.TextField(blank=True, default='', verbose_name='イベント紹介')),
                ('platform', models.CharField(choices=[('PC', 'PC オンリー'), ('All', 'Android/PC 対応'), ('Android', 'Android オンリー')], default='All', max_length=10, verbose_name='対応プラットフォーム')),
                ('tags', models.JSONField(choices=[('技術', '技術'), ('学術', '学術'), ('理系', '理系'), ('文系', '文系')], default=list, max_length=10, verbose_name='タグ')),
            ],
            options={
                'verbose_name': '集会',
                'verbose_name_plural': '集会',
                'db_table': 'community',
            },
        ),
    ]
