# Generated by Django 4.2.13 on 2024-06-16 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='集会名')),
                ('created_at', models.DateField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='開始日')),
                ('updated_at', models.DateField(auto_now=True, db_index=True, verbose_name='更新日')),
                ('end_at', models.DateField(blank=True, default=None, null=True, verbose_name='終了日')),
                ('start_time', models.TimeField(db_index=True, default='22:00', verbose_name='開始時刻')),
                ('duration', models.IntegerField(default=60, help_text='単位は分', verbose_name='開催時間')),
                ('weekdays', models.JSONField(blank=True, default=list, verbose_name='曜日')),
                ('frequency', models.CharField(max_length=100, verbose_name='開催周期')),
                ('organizers', models.CharField(max_length=200, verbose_name='主催・副主催')),
                ('group_url', models.URLField(blank=True, verbose_name='VRChatグループURL')),
                ('organizer_url', models.URLField(blank=True, verbose_name='主催プロフィールURL')),
                ('sns_url', models.URLField(blank=True, verbose_name='SNS')),
                ('discord', models.URLField(blank=True, verbose_name='Discord')),
                ('twitter_hashtag', models.CharField(blank=True, max_length=100, verbose_name='Twitterハッシュタグ')),
                ('poster_image', models.ImageField(blank=True, upload_to='poster/', verbose_name='ポスター')),
                ('description', models.TextField(blank=True, default='', verbose_name='イベント紹介')),
                ('platform', models.CharField(choices=[('PC', 'PC'), ('All', 'Android・PC'), ('Android', 'Android')], default='All', max_length=10, verbose_name='対応プラットフォーム')),
                ('tags', models.JSONField(default=list, max_length=10, verbose_name='タグ')),
                ('custom_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '集会',
                'verbose_name_plural': '集会',
                'db_table': 'community',
            },
        ),
    ]
