# Generated by Django 4.2.13 on 2024-06-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='community',
            table='community',
        ),
    ]
