# Generated by Django 4.2.13 on 2024-06-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='is_accepted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='公開設定'),
        ),
    ]
