# Generated by Django 4.2.13 on 2024-06-05 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='start_from',
        ),
        migrations.AddField(
            model_name='community',
            name='created_at',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='開始日'),
        ),
        migrations.AddField(
            model_name='community',
            name='updated_at',
            field=models.DateField(auto_now=True, db_index=True, verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='community',
            name='end_at',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='終了日'),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='集会名'),
        ),
        migrations.AlterField(
            model_name='community',
            name='organizer_url',
            field=models.URLField(blank=True, verbose_name='主催プロフィールURL'),
        ),
        migrations.AlterField(
            model_name='community',
            name='start_time',
            field=models.TimeField(db_index=True, default='22:00', verbose_name='開始時刻'),
        ),
    ]
