# Generated by Django 4.2.20 on 2025-04-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_community_is_accepted_community_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='allow_poster_repost',
            field=models.BooleanField(default=False, help_text='運営が集会のポスター画像をSNS等に転載してもよい場合はチェックしてください', verbose_name='ポスターを転載してもいいか'),
        ),
    ]
