# Generated by Django 4.2.13 on 2024-06-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_community_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='sns_url',
            field=models.URLField(blank=True, verbose_name='SNS'),
        ),
    ]
