# Generated by Django 4.2.13 on 2024-06-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_community_how_to_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='poster_image',
            field=models.ImageField(blank=True, upload_to='poster/', verbose_name='ポスター'),
        ),
    ]
