# Generated by Django 4.2.13 on 2024-06-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_community_sns_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='tags',
            field=models.JSONField(choices=[('技術', '技術'), ('学術', '学術')], default=list, max_length=10, verbose_name='タグ'),
        ),
    ]
