# Generated by Django 4.2.20 on 2025-04-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_community_allow_poster_repost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='allow_poster_repost',
            field=models.BooleanField(default=False, verbose_name='集会を紹介するためのポスターの転載を許可する'),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='集会紹介'),
        ),
    ]
