# Generated by Django 4.2.20 on 2025-06-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_community_allow_poster_repost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='allow_poster_repost',
            field=models.BooleanField(default=False, verbose_name='集会を紹介するためのポスター転載を許可する'),
        ),
    ]
