# Generated by Django 4.2.13 on 2024-06-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_community_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='weekday',
        ),
        migrations.AddField(
            model_name='community',
            name='weekdays',
            field=models.JSONField(blank=True, default=list, verbose_name='曜日'),
        ),
    ]
