# Generated by Django 4.2.27 on 2026-01-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_community_allow_poster_repost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='platform',
            field=models.CharField(choices=[('PC', 'PC'), ('All', 'PC / モバイル (Meta Quest 単体)'), ('Android', 'モバイル (Meta Quest 単体)')], default='All', max_length=10, verbose_name='対応プラットフォーム'),
        ),
    ]
