# Generated by Django 4.2.27 on 2026-01-26 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0007_alter_community_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '主催者'), ('staff', 'スタッフ')], default='staff', max_length=10, verbose_name='役割')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='追加日時')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='community.community', verbose_name='集会')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_memberships', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '集会メンバー',
                'verbose_name_plural': '集会メンバー',
                'unique_together': {('community', 'user')},
            },
        ),
    ]
