# Generated by Django 4.2.27 on 2026-01-26 07:36

from django.db import migrations


def migrate_custom_user_to_member(apps, schema_editor):
    """既存のCommunity.custom_userをCommunityMemberに移行する"""
    Community = apps.get_model('community', 'Community')
    CommunityMember = apps.get_model('community', 'CommunityMember')

    for community in Community.objects.filter(custom_user__isnull=False):
        CommunityMember.objects.get_or_create(
            community=community,
            user=community.custom_user,
            defaults={'role': 'owner'}
        )


def reverse_migrate(apps, schema_editor):
    """逆マイグレーション（何もしない）"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_add_community_member'),
    ]

    operations = [
        migrations.RunPython(migrate_custom_user_to_member, reverse_migrate),
    ]
