# Generated by Django 4.2.27 on 2026-01-27 08:27

from django.db import migrations


def migrate_admin_to_staff(apps, schema_editor):
    """古い 'admin' ロールを 'staff' に移行する"""
    CommunityMember = apps.get_model('community', 'CommunityMember')
    updated = CommunityMember.objects.filter(role='admin').update(role='staff')
    if updated:
        print(f'\n  {updated}件の admin ロールを staff に更新しました')


def reverse_migration(apps, schema_editor):
    """元に戻す（staff -> admin には戻さない）"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_communityinvitation'),
    ]

    operations = [
        migrations.RunPython(migrate_admin_to_staff, reverse_migration),
    ]
