# Generated by Django 4.2.27 on 2026-01-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_migrate_admin_to_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityinvitation',
            name='invitation_type',
            field=models.CharField(choices=[('staff', 'スタッフ招待'), ('ownership_transfer', '主催者引き継ぎ')], default='staff', max_length=20, verbose_name='招待タイプ'),
        ),
    ]
