# Generated by Django 4.2.27 on 2026-01-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_add_invitation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='notification_webhook_url',
            field=models.URLField(blank=True, default='', verbose_name='Discord Webhook URL'),
        ),
    ]
