# Generated by Django 4.2.27 on 2026-01-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_community_notification_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='accepts_lt_application',
            field=models.BooleanField(default=True, help_text='ONにすると、この集会でLT申請を受け付けます', verbose_name='LT申し込み受付'),
        ),
    ]
