# Generated by Django 4.2.27 on 2026-01-31 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_community_accepts_lt_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='lt_application_min_length',
            field=models.PositiveIntegerField(default=0, help_text='0の場合は文字数チェックを行いません', verbose_name='追加情報の最低文字数'),
        ),
        migrations.AddField(
            model_name='community',
            name='lt_application_template',
            field=models.TextField(blank=True, default='', help_text='LT申請時に登壇者に入力してもらいたい項目のテンプレート。空の場合は追加情報欄を表示しません。', verbose_name='LT申請テンプレート'),
        ),
        migrations.AlterField(
            model_name='community',
            name='accepts_lt_application',
            field=models.BooleanField(default=True, help_text='ONにすると、この集会で発表（LT）申請を受け付けます', verbose_name='発表（LT）申し込み受付'),
        ),
    ]
