# Generated by Django 4.2.27 on 2026-02-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_community_lt_application_min_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='default_lt_duration',
            field=models.PositiveIntegerField(default=30, help_text='LT申請フォームに表示されるデフォルトの発表時間（分）', verbose_name='デフォルトの発表時間'),
        ),
        migrations.AlterField(
            model_name='community',
            name='discord',
            field=models.URLField(blank=True, verbose_name='Discordサーバー'),
        ),
        migrations.AlterField(
            model_name='community',
            name='sns_url',
            field=models.URLField(blank=True, verbose_name='X（旧Twitter）'),
        ),
        migrations.AlterField(
            model_name='community',
            name='twitter_hashtag',
            field=models.CharField(blank=True, max_length=100, verbose_name='Xハッシュタグ'),
        ),
    ]
