# Generated by Django 4.2.27 on 2026-02-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_add_default_lt_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='custom_user',
        ),
    ]
