# Generated by Django 4.2.27 on 2026-02-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_remove_custom_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='lt_application_min_length',
        ),
    ]
