# Generated by Django 4.2.28 on 2026-03-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_remove_lt_application_min_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='discord_mention_role_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='DiscordロールID'),
        ),
        migrations.AddField(
            model_name='community',
            name='discord_mention_type',
            field=models.CharField(choices=[('none', 'メンションなし'), ('role', 'ロールメンション'), ('users', 'ユーザーメンション')], default='none', max_length=10, verbose_name='Discordメンション種別'),
        ),
        migrations.AddField(
            model_name='community',
            name='discord_mention_user_ids',
            field=models.JSONField(blank=True, default=list, help_text='例: ["123456789012345678", "987654321098765432"]', verbose_name='DiscordユーザーIDリスト'),
        ),
    ]
