# Generated by Django 4.2.28 on 2026-03-06 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_community_discord_mention_role_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='notification_webhook_url',
            field=models.URLField(blank=True, default='', validators=[django.core.validators.RegexValidator(message='Discord Webhook URL は https://discord.com/api/webhooks/ で始まる必要があります。', regex='^https://discord\\.com/api/webhooks/')], verbose_name='Discord Webhook URL'),
        ),
    ]
