# Generated by Django 4.2.28 on 2026-03-24 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0020_alter_community_notification_webhook_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='通報者IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='通報日時')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.community', verbose_name='集会')),
            ],
            options={
                'verbose_name': '活動停止通報',
                'verbose_name_plural': '活動停止通報',
            },
        ),
    ]
