# Generated by Django 4.2.29 on 2026-03-31 14:06

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_communityreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='poster_image',
            field=models.ImageField(blank=True, upload_to=community.models.poster_upload_path, verbose_name='ポスター'),
        ),
    ]
