# Generated by Django 4.2.30 on 2026-05-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0022_alter_community_poster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='accepts_lt_application',
            field=models.BooleanField(default=True, help_text='ONにすると、この集会で発表申請を受け付けます', verbose_name='発表申し込み受付'),
        ),
        migrations.AlterField(
            model_name='community',
            name='default_lt_duration',
            field=models.PositiveIntegerField(default=30, help_text='発表申請フォームに表示されるデフォルトの発表時間（分）', verbose_name='デフォルトの発表時間'),
        ),
        migrations.AlterField(
            model_name='community',
            name='lt_application_template',
            field=models.TextField(blank=True, default='', help_text='発表申請時に登壇者に入力してもらいたい項目のテンプレート。空の場合は追加情報欄を表示しません。', verbose_name='発表申請テンプレート'),
        ),
        migrations.AlterField(
            model_name='community',
            name='sns_url',
            field=models.URLField(blank=True, verbose_name='XアカウントURL'),
        ),
    ]
