# Generated by Django 4.2.30 on 2026-05-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0023_alter_community_accepts_lt_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='lt_start_offset_minutes',
            field=models.PositiveIntegerField(default=30, help_text='集会開始時刻から何分後にLTを開始するか（発表申請時のデフォルト値）', verbose_name='LT開始までのオフセット(分)'),
        ),
    ]
