# Generated by Django 4.2.30 on 2026-05-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0024_community_lt_start_offset_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='default_lt_duration',
            field=models.PositiveIntegerField(default=30, help_text='発表申請フォームに表示されるデフォルト値（分）。発表時間と質疑応答を含めた合計時間。', verbose_name='デフォルトの発表時間'),
        ),
    ]
