# Generated by Django 4.2.30 on 2026-06-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0025_alter_community_default_lt_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='communitymember',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='communitymember',
            constraint=models.UniqueConstraint(fields=('community', 'user'), name='community_member_unique_community_user'),
        ),
    ]
