# Generated by Django 5.2.14 on 2026-07-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0027_encrypt_notification_webhook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='default_lt_duration',
            field=models.PositiveIntegerField(default=30, help_text='発表申請フォームに表示されるデフォルト値（分）。発表と質疑応答を含めた合計時間。', verbose_name='発表の持ち時間（デフォルト）'),
        ),
    ]
