# Generated by Django 5.2.14 on 2026-07-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0028_alter_community_default_lt_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityActivityState",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("monitoring_enabled", models.BooleanField(default=True, help_text="季節開催・不定期開催など、自動判定に向かない集会はOFFにしてください。", verbose_name="自動監視を有効にする")),
                ("status", models.CharField(choices=[("unknown", "未確認"), ("active", "活動中"), ("suspected_inactive", "停止の可能性"), ("inactive", "活動停止"), ("uncertain", "判定不能"), ("error", "確認エラー")], db_index=True, default="unknown", max_length=24, verbose_name="活動状態")),
                ("consecutive_inactive_checks", models.PositiveSmallIntegerField(default=0, verbose_name="連続非活動判定回数")),
                ("inactive_detected_at", models.DateTimeField(blank=True, null=True, verbose_name="最初の非活動検知日時")),
                ("warning_sent_at", models.DateTimeField(blank=True, null=True, verbose_name="Discord警告送信日時")),
                ("auto_hidden_at", models.DateTimeField(blank=True, null=True, verbose_name="自動非表示日時")),
                ("last_checked_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="最終確認日時")),
                ("check_started_at", models.DateTimeField(blank=True, help_text="Cloud Runの多重実行を防ぐためのリース。異常終了時は一定時間後に再取得されます。", null=True, verbose_name="確認処理開始日時")),
                ("last_activity_at", models.DateField(blank=True, null=True, verbose_name="X上の最終活動日")),
                ("last_signal", models.CharField(blank=True, default="", max_length=32, verbose_name="最新判定シグナル")),
                ("last_confidence", models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name="最新判定の信頼度")),
                ("last_reason", models.TextField(blank=True, default="", verbose_name="最新判定理由")),
                ("last_evidence", models.JSONField(blank=True, default=list, verbose_name="最新根拠")),
                ("last_response_id", models.CharField(blank=True, default="", max_length=100, verbose_name="xAIレスポンスID")),
                ("last_model_name", models.CharField(blank=True, default="", max_length=100, verbose_name="xAIモデル")),
                ("last_cost_in_usd_ticks", models.BigIntegerField(blank=True, null=True, verbose_name="最新確認コスト(ticks)")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                ("community", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="activity_state", to="community.community", verbose_name="集会")),
            ],
            options={
                "verbose_name": "集会活動監視状態",
                "verbose_name_plural": "集会活動監視状態",
                "db_table": "community_activity_state",
            },
        ),
        migrations.CreateModel(
            name="CommunityActivityCheck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("result", models.CharField(choices=[("active", "活動中"), ("inactive", "活動停止"), ("uncertain", "判定不能"), ("error", "エラー")], db_index=True, max_length=16, verbose_name="判定")),
                ("signal", models.CharField(blank=True, default="", max_length=32, verbose_name="判定シグナル")),
                ("confidence", models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name="信頼度")),
                ("last_activity_at", models.DateField(blank=True, null=True, verbose_name="X上の最終活動日")),
                ("reason", models.TextField(blank=True, default="", verbose_name="判定理由")),
                ("evidence", models.JSONField(blank=True, default=list, verbose_name="根拠")),
                ("response_id", models.CharField(blank=True, default="", max_length=100, verbose_name="xAIレスポンスID")),
                ("model_name", models.CharField(blank=True, default="", max_length=100, verbose_name="xAIモデル")),
                ("cost_in_usd_ticks", models.BigIntegerField(blank=True, null=True, verbose_name="コスト(ticks)")),
                ("action", models.CharField(choices=[("none", "変更なし"), ("warned", "Discord警告"), ("hidden", "自動非表示")], default="none", max_length=16, verbose_name="実行した処理")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="確認日時")),
                ("community", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="activity_checks", to="community.community", verbose_name="集会")),
            ],
            options={
                "verbose_name": "集会活動確認履歴",
                "verbose_name_plural": "集会活動確認履歴",
                "db_table": "community_activity_check",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="communityactivitystate",
            index=models.Index(fields=["monitoring_enabled", "last_checked_at"], name="comm_act_due_idx"),
        ),
        migrations.AddIndex(
            model_name="communityactivitycheck",
            index=models.Index(fields=["community", "created_at"], name="comm_act_hist_idx"),
        ),
        migrations.AddIndex(
            model_name="communityactivitycheck",
            index=models.Index(fields=["result", "created_at"], name="comm_act_result_idx"),
        ),
    ]
