# Generated by Django 5.2.14 on 2026-09-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0028_alter_community_default_lt_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='recording_allowed',
            field=models.BooleanField(default=True, help_text='オフにすると、この集会の発表はハブの自動撮影の対象になりません', verbose_name='撮影を許可する'),
        ),
    ]
