# Generated by Django 5.2.17 on 2026-10-07 06:49

from django.db import migrations, models

# 撮影を許可していない集会のデフォルトは「禁止」にそろえる（「公開」のままだと設定どうしが矛盾する）。
# 許可している集会は列の既定値「公開」のまま（これまでの申請フォームの初期値と同じ）。
FORBIDDEN = 'forbidden'


def set_forbidden_for_disallowed_communities(apps, schema_editor):
    Community = apps.get_model('community', 'Community')
    Community.objects.filter(recording_allowed=False).update(default_recording_policy=FORBIDDEN)


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0030_remove_recording_line_from_default_lt_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='default_recording_policy',
            field=models.CharField(choices=[('forbidden', '禁止（撮影しない）'), ('allowed', '許可（撮影するが公開しない）'), ('public', '公開（撮影して YouTube で公開）')], db_default='public', default='public', help_text='発表申請フォームで、撮影の選択肢の初期値になります', max_length=20, verbose_name='デフォルトの撮影ステータス'),
        ),
        # 逆方向は列ごと消えるので何もしない
        migrations.RunPython(set_forbidden_for_disallowed_communities, migrations.RunPython.noop),
    ]
